services:
  - type: web
    name: king-xd-v6
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_ID
        sync: false   # You will input the Session ID in the Render dashboard
